SPOTIFY_URL = "https://accounts.spotify.com"
SPOTIFY_API_URL = "https://api.spotify.com"
SPOTIFY_ACCESS_TOKEN_ENDPOINT = f"{SPOTIFY_URL}/api/token"
SPOTIFY_ARTIST_ENDPOINT = f"{SPOTIFY_API_URL}/v1/artists/4Z8W4fKeB5YxbusRsdQVPb"
SPOTIFY_SEARCH_ENDPOINT = f"{SPOTIFY_API_URL}/v1/search"
SPOTIFY_PLAYLIST_ENDPOINT = f"{SPOTIFY_API_URL}/v1/playlists"
SPOTIFY_SIZE_PAGE = 10
SPOTIFY_SEARCH_TYPE_TRACK = "track"
SPOTIFY_PLAYLIST_ID = "62SUSaw1MuupOsaCwaf7Sn"
SPOTIFY_SEARCH_KEYWORD = "a"
SPOTIFY_SEARCH_DEFAULT_MAX_RESPONSE_SIZE = 20

DEFAULT_SIZE_RECORD = 100

NAMESPACE = "SpotifyTrack"
